"packages":
    [
        "common/**",
        "examples/**",
        "experimental/*/*",
        "packages/*/*",
        "server/azure-local-service",
        # "server/routerlicious/packages/*",
        # "server/routerlicious/packages/gitresources",
        "server/tinylicious",
        "tools/**",
    ]

link-workspace-packages: deep
prefer-workspace-packages: true
save-workspace-protocol: false
shared-workspace-lockfile: true
