"packages":
    [
        "common/**",
        "examples/**",
        "experimental/dds/**",
        "experimental/examples/bubblebench/*",
        "experimental/framework/*",
        "experimental/PropertyDDS/packages/*",
        "packages/*/*",
        "server/azure-local-service",
        "server/routerlicious/packages/*",
        # "server/routerlicious/packages/gitresources",
        "server/tinylicious",
        "tools/**",
        "scripts"
    ]

link-workspace-packages: deep
prefer-workspace-packages: true
save-workspace-protocol: false
shared-workspace-lockfile: true
